# Copy file to planeur.net FTP server

name: 1.3 - Create XCSoar files

# Controls when the workflow will run
on:
  # Triggers the workflow After the version has been added
  workflow_run:
    workflows: ["1.2 - Create .kmz"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# see: https://github.com/marketplace/actions/ftp-deployment
jobs:
  convert-to-kmz:
    name: Checkout repo for cup
    runs-on: ubuntu-latest
    steps:

    - name: 🚚 Get latest code for outlanding
      uses: actions/checkout@v3
      with:
        path: ./outlanding

    - name: 🚚 Get latest code for Landewiese-to-XCSoar-Waypoints
      uses: actions/checkout@v3
      with:
        repository: llauner/Landewiese-to-XCSoar-Waypoints
        path: ./Landewiese-to-XCSoar-Waypoints
        ref: master

    - name: 🚚 Get latest code for ReFirmLabs/binwalk
      uses: actions/checkout@v3
      with:
        repository: ReFirmLabs/binwalk
        path: ./binwalk
        ref: master
    
    - name: ⚙️ Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.11' 
    
    - name: Install dependencies
      run: | 
        echo "### Install Python requirements.txt..."
        cd ./Landewiese-to-XCSoar-Waypoints
        mkdir data
        pip install -r requirements.txt
        
        echo "### Install binwalk..."
        cd ../binwalk
        sudo python setup.py install
        
        echo "### Execute Python ..."
        cd ../
        cp ./outlanding/guide_aires_securite.cupx ./Landewiese-to-XCSoar-Waypoints/data
        cd ./Landewiese-to-XCSoar-Waypoints
        python ./convert.py guide_aires_securite


    - name: ⚙️ Push .kml + .kmz to repo
      if: ${{ false }}
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        repository: ./outlanding
        file_pattern: 'guide_aires_securite.kml guide_aires_securite.kmz'


