# Copy file to planeur.net FTP server

name: 1.3 - Create XCSoar _details.txt file

# Controls when the workflow will run
on:
  # Triggers the workflow After the version has been added
  # workflow_run:
  #   workflows: ["1.2 - Create .kmz"]
  #   types:
  #     - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# see: https://github.com/marketplace/actions/ftp-deployment
jobs:
  convert-to-kmz:
    name: Checkout repo for cup
    runs-on: ubuntu-latest
    steps:

    - name: 🚚 Get latest code for outlanding
      uses: actions/checkout@v3
      with:
        path: ./outlanding

    - name: 🚚 Get latest code for cup2xcsoar
      uses: actions/checkout@v3
      with:
        repository: llauner/cup2xcsoar
        token: ${{ secrets.ACCESS_TOKEN_CUP2KMZ }}
        path: ./cup2xcsoar
        ref: master

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: | 
        cd ./cup2xcsoar
        npm install
    
    - name: ⚙️ Create _details.txt
      id: create_details
      run: |
        echo "### Create guide_aires_securite_details.txt"
        cd ./cup2xcsoar
        node ./cupToXCSoar.js ../outlanding/guide_aires_securite.cup

        echo "### Copy _details to outlanding repo location"
        cp ./guide_aires_securite_details.txt ../outlanding/

        # push to repo
        echo "Pulling latest version before push..."
        cd ../outlanding
        git pull

        # Save commit message for future push
        echo "LAST_COMMIT_MESSSAGE=`git log --format=%s -n 1 -- champs_des_alpes.cup`" >> $GITHUB_OUTPUT

    # - name: ⚙️ Push guide_aires_securite_details.txt to repo
    #   uses: stefanzweifel/git-auto-commit-action@v5
    #   with:
    #     repository: ./outlanding
    #     commit_message: ${{ steps.create_details.outputs.LAST_COMMIT_MESSSAGE }}
    #     file_pattern: 'guide_aires_securite_details.txt'


