# Copy file to planeur.net FTP server

name: 1.3 - Create XCSoar files

# Controls when the workflow will run
on:
  # Triggers the workflow After the version has been added
  # workflow_run:
  #   workflows: ["1.2 - Create .kmz"]
  #   types:
  #     - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# see: https://github.com/marketplace/actions/ftp-deployment
jobs:
  convert-to-kmz:
    name: Checkout repo for cup
    runs-on: ubuntu-latest
    steps:

    - name: 🚚 Get latest code for outlanding
      uses: actions/checkout@v3
      with:
        path: ./outlanding

    - name: 🚚 Get latest code for Landewiese-to-XCSoar-Waypoints
      uses: actions/checkout@v3
      with:
        repository: llauner/Landewiese-to-XCSoar-Waypoints
        path: ./Landewiese-to-XCSoar-Waypoints
        ref: master

    - name: 🚚 Get latest code for ReFirmLabs/binwalk
      uses: actions/checkout@v3
      with:
        repository: ReFirmLabs/binwalk
        path: ./binwalk
        ref: master
    
    - name: ⚙️ Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.11' 
    
    - name: Install dependencies and execute convertion
      run: | 
        echo "### Install Python requirements.txt..."
        cd ./Landewiese-to-XCSoar-Waypoints
        mkdir data
        pip install -r requirements.txt
        
        echo "### Install binwalk..."
        cd ../binwalk
        python setup.py install
        python setup.py uninstall
        python setup.py install 
        
        echo "### Execute Python ..."
        cd ../
        cp ./outlanding/guide_aires_securite.cupx ./Landewiese-to-XCSoar-Waypoints/data
        cd ./Landewiese-to-XCSoar-Waypoints
        python ./convert.py guide_aires_securite

        echo "### Copy output to oulanding repo"
        cp -r ./output/docs ../outlanding/xcsoar_waypoint_details/
        cp -r ./output/pics ../outlanding/xcsoar_waypoint_details/
        cp ./output/guide_aires_securite.wp_details.txt ../outlanding/xcsoar_waypoint_details/


    - name: ⚙️ Push output directory to repo
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        repository: ./outlanding
        file_pattern: './xcsoar_waypoint_details/*'


