# Copy file to planeur.net FTP server

name: 2.1 - Create .kmz

# Controls when the workflow will run
on:
  # Triggers the workflow After the version has been added
  workflow_run:
    workflows: ["1 - Add version to guide_aires_securite.cup"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# see: https://github.com/marketplace/actions/ftp-deployment
jobs:
  convert-to-kmz:
    name: Checkout repo for cup
    runs-on: ubuntu-latest
    steps:

    - name: 🚚 Get latest code for outlanding
      uses: actions/checkout@v3
      with:
        path: ./outlanding

    - name: 🚚 Get latest code for cup2kmz
      uses: actions/checkout@v3
      with:
        repository: llauner/cup2kmz
        token: ${{ secrets.ACCESS_TOKEN_CUP2KMZ }}
        path: ./cup2kmz
        ref: master

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: | 
        cd ./cup2kmz
        npm install
    
    - name: ⚙️ Convert to .cup to .cupx and push to repo
      run: |
        cd ./cup2kmz
        node ./cuptokmz.js

        # push to repo
        echo "Pulling latest version before push..."
        cd ../outlanding
        git pull

    - name: ⚙️ Push .cub to repo
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        repository: ./outlanding
        commit_message: Automated Change
        file_pattern: 'guide_aires_securite.kmz'


